allure.results.directory=target/allure-results
allure.link.pattern=https://shopsphere.atlassian.net/browse/{}
allure.link.issue.pattern=https://shopsphere.atlassian.net/browse/{}
allure.link.tms.pattern=https://shopsphere.testrail.com/index.php?/tests/view/{}
