package com.shopsphere.api.contract;

import au.com.dius.pact.provider.junit5.HttpsTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;

/**
 * Provider Contract Verification Test.
 *
 * Verifies that FakeStoreAPI (the provider) honours the contracts
 * defined by the consumer (ProductConsumerContractTest).
 *
 * How it works:
 *   1. Reads pact files from target/pacts/ (generated by consumer test)
 *   2. Replays each interaction against the real FakeStoreAPI
 *   3. Verifies the responses match what the consumer expects
 *
 * Run order in CI:
 *   Step 1: Consumer test runs → generates target/pacts/*.json
 *   Step 2: Provider test runs → reads those pacts → verifies against fakestoreapi.com
 */
@Provider("FakeStoreProductService")
@PactFolder("target/pacts")
@DisplayName("FakeStore Product Service Provider Verification")
public class ProductProviderContractTest {

    @BeforeEach
    void setupTarget(PactVerificationContext context) {
        // Point at the real FakeStoreAPI — port 443, HTTPS
        context.setTarget(new HttpsTestTarget("fakestoreapi.com", 443));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    // ─── Provider States ──────────────────────────────────────────────────
    // These match the "given" clauses in the consumer test.
    // For FakeStoreAPI we don't need to set up data — it's always there.

    @State("products exist")
    public void productsExist() {
        // FakeStoreAPI always has products — nothing to set up
    }

    @State("product with id 1 exists")
    public void productWithId1Exists() {
        // FakeStoreAPI always has product id=1 — nothing to set up
    }

    @State("product with id 999 does not exist")
    public void productWithId999DoesNotExist() {
        // FakeStoreAPI returns 404 for id=999 — nothing to set up
    }
}
