base.url=https://www.saucedemo.com
api.base.url=http://localhost:8080/api/v1
mobile.base.url=http://localhost:8080/api/v1
browser=chrome
headless=false
implicit.wait=10
explicit.wait=20
admin.username=standard_user
admin.password=secret_sauce
