base.url=https://www.saucedemo.com
api.base.url=https://api.shopsphere.com/v1
mobile.base.url=https://api.shopsphere.com/v1
browser=chrome
headless=true
implicit.wait=10
explicit.wait=20
admin.username=${PROD_USERNAME}
admin.password=${PROD_PASSWORD}
